nome: Enviar filófo do dia

em:
 horário:
    - cron: '0 13 *'0 13 * * *'  # Envia às 10 h da manhã (horário Brasília)
 fluxo de trabalho_despacho:

empregos:
 enviar_filosofos:
 corre: ubuntu-último
 passos:
    - usos: ações/checkout@v3
    - nome: Configurar Python
 usos: ações/setup-python@v4
 com:
 versão python: '3,10'
    - nome: Instalar dependências
 corredor: pip instalar - r requisitos.txt
    - nome: Rodar o bot
 env:
 OPENAI_API_KEY: ${{ segredos.OPENAI_API_KEY }}
 DISCORD_TOKEN: ${{ segredos.DISCORD_TOKEN }}
 CANAL_ID: ${{ segredos.CHANNEL_ID }}
 corredor: python main.py
